name: Build and Release Windows TTS

on:
  workflow_dispatch:
  
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest  # 必须用 Windows 环境！

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Tidy and verify
        run: |
          go mod tidy
#          git diff --exit-code go.mod go.sum 

      - name: Build Windows executable
        run: |
          go build -ldflags="-s -w -X main.version=${{ env.VERSION }}" -o bin/win-tts-api.exe .

      - name: Upload Artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: tts-windows
          path: bin/win-tts-api.exe
